spring:
  application:
    name: product-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:5434/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
management:
  tracing:
    enabled: true
    sampling.probability: 1.0


springdoc:
  show-actuator: true

server:
  port: 8080
  error:
    include-message: always