spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  endpoints:
    web:
      exposure:
        include: liquibase, health, prometheus
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true


springdoc:
  show-actuator: true

server:
  port: 8080
  error:
    include-message: always
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:security/dev_product_service_keystore.p12
#    key-store-password: securepassword
#    protocol: TLS
#    enabled-protocols: TLSv1.2
#    trust-store: classpath:security/dev_product_service_truststore.p12
#    trust-store-password: securepassword

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/changeset/test/db.changelog-master-test.yml
management:
  endpoints:
    web:
      exposure:
        include: liquibase, health, mappings
