spring:
  application:
    name: product-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:5434/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
management:
  tracing:
    enabled: true
    sampling.probability: 1.0


management:
  endpoints:
    web:
      exposure:
        include: liquibase, health

springdoc:
  show-actuator: true

server:
  port: 8080
  error:
    include-message: always

  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:security/dev_product_service_keystore.p12
    key-store-password: securepassword
    protocol: TLS
    enabled-protocols: TLSv1.2
    trust-store: classpath:security/dev_product_service_truststore.p12
    trust-store-password: securepassword